name: "Hello Demo Action"
description: "A simple custom GitHub Action for demo"
author: "Your Name"

inputs:
  name:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "composite"
  steps:
    - name: Say hello
      shell: bash
      run: echo "👋 Hello, ${{ inputs.name }}! This is your custom composite action running!"
