name: "Hello Demo Action"
description: "A simple custom GitHub Action for demo"
author: "Your Name"

inputs:
  name:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "node16"
  main: "index.js"
