name: Demo Workflow

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run custom hello action
        uses: ./.github/actions/hello-action
        with:
          name: "Surya"
